DROP TABLE IF EXISTS autoshops;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id serial PRIMARY KEY,
    username text UNIQUE,
    password text,
    shopName text,
    created timestamp DEFAULT now()
);

INSERT INTO users 

CREATE TABLE autoshops (
  id serial PRIMARY KEY,
  name text NOT NULL,
  street text,
  city text,
  state text, 
  zip text,
  phone text,
  monday text,
  tuesday text,
  wednesday text,
  thursday text,
  friday text,
  saturday text,
  sunday text,
  oilChanges boolean,
  batteryInstallation boolean,
  filterReplacement boolean,
  fluidExchanges boolean,
  fuelSystemServices boolean,
  scheduledOEMaintenance boolean,
  winterPrepPackage boolean,
  summerPrepPackage boolean,
  wheelAlignment boolean,
  tireRepair boolean,
  tireInstallation boolean,
  acHeat boolean,
  beltsAndHoses boolean,
  brakeServices boolean,
  diagnostics boolean,
  checkEngine boolean,
  suspension boolean,
  performance boolean,
  carAudio boolean,
  stateInspection boolean,
  transmissions boolean,
  created timestamp DEFAULT now()
);

INSERT INTO autoshops
    (
        name,
        street,
        city,
        state, 
        zip,
        phone,
        monday,
        tuesday,
        wednesday,
        thursday,
        friday,
        saturday,
        sunday,
        oilChanges,
        batteryInstallation,
        filterReplacement,
        fluidExchanges,
        fuelSystemServices,
        scheduledOEMaintenance,
        winterPrepPackage,
        summerPrepPackage,
        wheelAlignment,
        tireRepair,
        tireInstallation,
        acHeat,
        beltsAndHoses,
        brakeServices,
        diagnostics,
        checkEngine,
        suspension,
        performance,
        carAudio,
        stateInspection,
        transmissions
    ) VALUES
    (
        'Kako Transmissions',
        '15430 S Vermont Ave',
        'Gardena',
        'CA',
        '90247',
        '(310) 515-0008',
        '8AM-5PM',
        '8AM-5PM',
        '8AM-5PM',
        '8AM-5PM',
        '8AM-5PM',
        '8AM-12PM',
        'Closed',
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    ),
    (
        'Pep Boys Auto Parts & Services',
        '1135 E Colorado Blvd',
        'Pasadena',
        'CA',
        '91106',
        '(626) 793-8181',
        '7:30AM-8PM',
        '7:30AM-8PM',
        '7:30AM-8PM',
        '7:30AM-8PM',
        '7:30AM-8PM',
        '7:30AM-8PM',
        '9AM-6PM',
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false
    )
    RETURNING id, name;